#!/usr/bin/env python3
"""Prepare GPUI main sources; --freeze records tested revisions for release.

The component repository publishes GPUI under gpui-pre package names. A manifest
overlay connects its source to Zed's original workspace; no source is vendored
in the project. Reviewed source patches live in desktop/patches and are replayed
after checkout. Developer checkouts remain untouched except for fast-forward pulls.
"""
import argparse
import json
from pathlib import Path
import re
import shutil
import subprocess
import tempfile

ROOT = Path(__file__).resolve().parents[1]
REPOS = {"zed": "zed-industries/zed", "component": "longbridge/gpui-component"}
DEFAULT_DEVELOPER_DIR = ROOT.parent.parent / "course2md-dependencies"


def git(path, *args, capture=False, lf=False):
    options = ["-c", "core.autocrlf=false"] if lf else []
    result = subprocess.run(["git", *options, "-C", str(path), *args], check=True,
                            text=True, stdout=subprocess.PIPE if capture else None)
    return result.stdout.strip() if capture else None


def source_patches(name):
    return sorted((ROOT / "patches").glob(f"{name}-*.patch"))


def patch_paths(patches):
    paths = set()
    for patch in patches:
        for line in patch.read_text(encoding="utf-8").splitlines():
            if line.startswith("+++ b/"):
                path = line[6:]
                if Path(path).is_absolute() or ".." in Path(path).parts:
                    raise SystemExit(f"Unsafe path in reviewed patch {patch}: {path}")
                paths.add(path)
    return paths


def component_overlay(path, content):
    if path == "Cargo.toml":
        text = content.decode()
        for alias, crate in [("gpui", "gpui"), ("gpui_platform", "gpui_platform"),
                             ("gpui_macros", "gpui_macros"), ("sum-tree", "sum_tree"),
                             ("reqwest_client", "reqwest_client"), ("gpui_web", "gpui_web")]:
            pattern = rf'^{re.escape(alias)} = \{{ package = "gpui-pre[^\"]*",[^\n]*\}}$'
            features = ', features = ["font-kit", "x11", "wayland", "runtime_shaders"]' if alias == "gpui_platform" else ''
            package = f', package = "{crate}"' if alias != crate else ''
            replacement = f'{alias} = {{ path = "../zed/crates/{crate}"{package}{features} }}'
            text, count = re.subn(pattern, replacement, text, count=1, flags=re.M)
            if count != 1:
                raise SystemExit(f"Upstream changed the {alias} dependency; review the manifest overlay")
        return text.encode()
    if path == "crates/component-macros/src/crate_path.rs":
        old = b'Err(kit_error) => crate_name("gpui-pre")'
        if content.count(old) != 1:
            raise SystemExit("Upstream macro lookup changed; review the compatibility patch")
        return content.replace(old, old + b'.or_else(|_| crate_name("gpui"))')
    return content


def apply_patch(directory, patch, *, reverse=False, check=False):
    args = ["git", "-c", "core.autocrlf=false", "apply"]
    if reverse:
        args.append("--reverse")
    if check:
        args.append("--check")
    args.append(str(patch))
    return subprocess.run(args, cwd=directory, check=False, capture_output=True, text=True)


def head_bytes(directory, revision, path):
    return subprocess.run(["git", "-C", str(directory), "show", f"{revision}:{path}"],
                          check=True, stdout=subprocess.PIPE).stdout


def verify_and_restore_overlay(directory, name, patches):
    """Only discard exact generated bytes; never discard edits to patched files."""
    changed = git(directory, "diff", "HEAD", "--name-only", capture=True).splitlines()
    if not changed:
        return
    paths = set(changed) | patch_paths(patches)
    with tempfile.TemporaryDirectory(prefix="course2md-overlay-check-") as temporary:
        staged = Path(temporary)
        for path in paths:
            target = staged / path
            target.parent.mkdir(parents=True, exist_ok=True)
            if not (directory / path).is_file() or (directory / path).is_symlink():
                raise SystemExit(f"Unexpected source edit in {directory}: {path}")
            shutil.copyfile(directory / path, target)
        # Reverse in a disposable copy, so a failed verification changes no
        # real dependency files. Forward-check also accepts a clean checkout.
        for patch in reversed(patches):
            if apply_patch(staged, patch, reverse=True, check=True).returncode == 0:
                result = apply_patch(staged, patch, reverse=True)
            else:
                result = apply_patch(staged, patch, check=True)
            if result.returncode:
                raise SystemExit(f"Unexpected edits or changed patch in {directory}: {patch.name}\n{result.stderr}")
        for path in paths:
            expected = head_bytes(directory, "HEAD", path)
            if name == "component":
                expected = component_overlay(path, expected)
            if (staged / path).read_bytes() != expected:
                raise SystemExit(f"Unexpected source edit in {directory}: {path}; original file preserved")
    git(directory, "restore", "--source=HEAD", "--staged", "--worktree", *changed, lf=True)


def verify_patch_revision(directory, revision, patches):
    """Check the complete overlay against the requested revision before checkout."""
    with tempfile.TemporaryDirectory(prefix="course2md-patch-check-") as temporary:
        staged = Path(temporary)
        for path in patch_paths(patches):
            target = staged / path
            target.parent.mkdir(parents=True, exist_ok=True)
            target.write_bytes(head_bytes(directory, revision, path))
        for patch in patches:
            result = apply_patch(staged, patch)
            if result.returncode:
                raise SystemExit(f"Upstream changed; review {patch.name} before preparing sources:\n{result.stderr}")


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    mode = parser.add_mutually_exclusive_group()
    mode.add_argument("--no-pull", action="store_true", help="Reuse already updated local main sources")
    mode.add_argument("--freeze", action="store_true", help="Record currently prepared and tested source revisions")
    mode.add_argument("--locked", action="store_true", help="Use release source revisions without updating main")
    parser.add_argument("--developer-dir", type=Path, default=DEFAULT_DEVELOPER_DIR)
    args = parser.parse_args()
    lock_path = ROOT / "sources.lock.json"
    if args.freeze:
        revisions = {name: git(ROOT / ".deps" / name, "rev-parse", "HEAD", capture=True) for name in REPOS}
        lock_path.write_text(json.dumps(revisions, indent=2) + "\n")
        print(f"Recorded tested revisions in {lock_path}")
        return
    locked = json.loads(lock_path.read_text()) if args.locked else {}
    if args.locked and (set(locked) != set(REPOS) or
                        any(not re.fullmatch(r"[0-9a-f]{40}", value) for value in locked.values())):
        raise SystemExit("Release source lock must contain a full commit hash for each dependency")
    (ROOT / ".deps").mkdir(exist_ok=True)
    for name, remote in REPOS.items():
        source = args.developer_dir / ("gpui-component" if name == "component" else "zed")
        if not source.exists():
            source.parent.mkdir(parents=True, exist_ok=True)
            subprocess.run(["git", "clone", f"https://github.com/{remote}.git", str(source)], check=True)
        if not args.locked and not args.no_pull:
            if git(source, "status", "--porcelain", capture=True):
                raise SystemExit(f"Commit or stash changes in {source} before pulling main")
            if git(source, "branch", "--show-current", capture=True) != "main":
                raise SystemExit(f"{source} must be on main")
            git(source, "pull", "--ff-only", f"https://github.com/{remote}.git", "main")
        revision = locked.get(name) or git(source, "rev-parse", "HEAD", capture=True)
        dest = ROOT / ".deps" / name
        patches = source_patches(name)
        verify_patch_revision(source, revision, patches)
        if not dest.exists():
            git(source, "worktree", "add", "--detach", str(dest), revision, lf=True)
        else:
            verify_and_restore_overlay(dest, name, patches)
            git(dest, "checkout", "--detach", revision, lf=True)
        if name == "component":
            for path in ["Cargo.toml", "crates/component-macros/src/crate_path.rs"]:
                file = dest / path
                file.write_bytes(component_overlay(path, file.read_bytes()))
        for patch in patches:
            result = apply_patch(dest, patch)
            if result.returncode:
                raise SystemExit(f"Could not apply reviewed patch {patch.name}:\n{result.stderr}")
    print("Prepared GPUI and GPUI Component sources with reviewed patches")


if __name__ == "__main__":
    main()
